name: Release Docker Image

on:
  push:
    branches:
      - fork
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.1'
      - name: Tidy
        run: |
          rm -f go.sum
          go mod tidy
      - name: Build coredns
        run: make coredns
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cmacrae/coredns
          tag_with_ref: true
          add_git_labels: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
